name: Publish Docker Images

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on PR to the main branch

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub using an Access Token
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: dannycarrera
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      # Build and push the backend Docker image
      - name: Build and push backend image
        run: |
          docker build --build-arg REACT_APP_BACKEND_URL=https://api.rag-ai-chatbot.danielcarrera.dev -t dannycarrera/rag-ai-chatbot-backend:latest ./backend
          docker push dannycarrera/rag-ai-chatbot-backend:latest

      # Build and push the frontend Docker image
      - name: Build and push frontend image
        run: |
          docker build -t dannycarrera/rag-ai-chatbot-frontend:latest ./frontend
          docker push dannycarrera/rag-ai-chatbot-frontend:latest